#!/bin/sh /etc/rc.common
# Copyright (C) 2019-2022 wulishui <wulishui@gmail.com>
# 20190805-20220906

START=99
USE_PROCD=1

start_instance() {
 procd_open_instance
 procd_set_param command /usr/bin/cowbpingd
 procd_set_param respawn
 procd_set_param stderr 1
 procd_close_instance
}

start_service() {
 stop_service
 enabled=$(uci -q get cowbping.cowbping.enabled)
 if [ "$enabled" == 1 ]; then
   cat /dev/null > /tmp/log/cowbping.log
   start_instance
 fi
}

stop_service() {
  cat /dev/null > /tmp/log/cowbping.log
  kill -9 $(busybox ps |egrep 'cbp_cmd|cowbpingd' |grep -v 'grep' |awk '{print $1}') >/dev/null 2>&1
}

restart() {
 stop_service
 start_service
}
